### ISSUE TITLE
Getting grades on submitted values

### ISSUE THREAD

**Issue by sanobertin** [MicrosoftLearning/Principles-of-Machine-Learning-Python#5]
During the final exam of the course <b>Principles of Machine Learning: Python Edition</b>  regarding with this repo I'm getting this error(in image) while trying to submit my predicted values and receive grades. I'm using https://datahack4fi.21cskills.africa/ platfrom but the content is embedded from edx with the course <b>Principles of Machine Learning: Python Edition</b> <br>
If someone has faced this issue like mine, help me also to resolve it

![screen shot 2018-12-30 at 23 31 39](https://user-images.githubusercontent.com/38949731/50551570-3c1c8400-0c8b-11e9-9392-e1c50f86b7f9.png)

**Comment by StephenElston** [comment]
I am sorry, but I am not seeing an error in the screen shot. Can you please explain further. Thank you.

**Comment by sanobertin** [comment]
So as I have to submit the predicted values in that excel sheet, edx automatically creates a code to input down there( in order to get grades based on what I submitted)  as I showed then when I click on submit button I get that error display below the <b>submit</b> button. Actually the error may be that it comes from the web itself(https://datahack4fi.21cskills.africa/) but the reason I asked here is because that website embeds courses from directly from edx <br>
![screen shot 2019-01-05 at 01 36 28](https://user-images.githubusercontent.com/38949731/50716482-72427500-108a-11e9-9c65-9ee7af28c102.png)

**Comment by StephenElston** [comment]
Hi.

This does not look like a problem with the code in this repository. Therefore, I think the course support team can best help you. I suggest that you post this issue in the edX course Discussion (under the Discussion tab). 

I am marking this issue as resolved, since the problem lies outside this repository.
